schema_version: 1
id: pantsagon.docker
version: 1.0.0
description: Docker feature pack
compatibility:
  pants: ">=2.30.0,<2.31"
requires:
  packs:
    - pantsagon.core
    - pantsagon.python
provides:
  features:
    - docker
variables:
  - name: service_name
    type: string
  - name: service_pkg
    type: string
