name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PANTSAGON_DETERMINISTIC: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Init Pants
        uses: pantsbuild/actions/init-pants@v10
        with:
          named-caches-hash: ${{ hashFiles('3rdparty/python/requirements.txt', 'docs/requirements.txt') }}
      - name: Pants test
        run: |
          pants test --test-use-coverage ::
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: dist/coverage/python/coverage.xml
          flags: pants
          name: pants
          fail_ci_if_error: false
